[project]
name = "learn2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adi Kadimetla", email = "kadimetla@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
]

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
